services:
  - type: web
    name: knoxai1
    env: python
    runtime: python-3.11.8
    buildCommand: "pip3 install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"
    autoDeploy: true